/**
 * Constants for various date and time formats
 */
const DateTimeFormats = {
    BASIC_ISO_DATE: "BASIC_ISO_DATE",
    ISO_LOCAL_DATE: "ISO_LOCAL_DATE",
    ISO_OFFSET_DATE: "ISO_OFFSET_DATE",
    ISO_DATE: "ISO_DATE",
    ISO_LOCAL_TIME: "ISO_LOCAL_TIME",
    ISO_OFFSET_TIME: "ISO_OFFSET_TIME",
    ISO_TIME: "ISO_TIME",
    ISO_LOCAL_DATE_TIME: "ISO_LOCAL_DATE_TIME",
    ISO_OFFSET_DATE_TIME: "ISO_OFFSET_DATE_TIME",
    ISO_ZONED_DATE_TIME: "ISO_ZONED_DATE_TIME",
    ISO_DATE_TIME: "ISO_DATE_TIME",
    ISO_ORDINAL_DATE: "ISO_ORDINAL_DATE",
    ISO_WEEK_DATE: "ISO_WEEK_DATE",
    ISO_INSTANT: "ISO_INSTANT",
    RFC_1123_DATE_TIME: "RFC_1123_DATE_TIME",
    ISO_OFFSET_DATE_TIME_EXPLICIT: "uuuu-MM-dd'T'HH:mm:ssxxx"
};

export default DateTimeFormats; 