module.exports = [
  "ui/ShipmentDetails/TC_Additional_Details_01_Verify_that_the_Timestamps_display_Information_Received_as_a_most_outstanding_feature.spec.js",
  "ui/ShipmentDetails/TC_Additional_Details_02_Verify_that_the_Timestamps_display_Picked_Up_as_a_most_outstanding_feature.spec.js",
  "ui/ShipmentOverview/TC_Additional_Details_03_Verify_that_the_Timestamps_display_Processing_and_another_one_as_a_most_outstanding_feature.spec.js",
  "ui/ShipmentOverview/TC_Additional_Details_04_Verify_that_the_Timestamps_display_First_Delivery_Attempt_as_a_most_outstanding_feature.spec.js"
]; 